### PR TITLE
Made blank equal true

### PR DESCRIPTION
**Pull request by pillsbury7901**
Changes made in response to bug report:  Allow comment and description fields to remain empty #18

### CODE REVIEW

**Comment by tibonihoo** [comment]
Thanks for this contribution. I'm just a little surprised that there is no migration file added to wom_user/migrations. These are generated by django-south when you tell is that the db scheme has changed and they are very important to update the dbs of existing wateronmars installations.

Did you have a chance to use south ?

**Comment by pillsbury7901** [comment]
I believe that I did everything as instructed...It is possible that I could have made a mistake as I am not very familiar with using south. What can I do to correct the problem?

**Comment by tibonihoo** [comment]
Just a heads up (from me), I've had no internet at home for one month, I'll try to find some time to look into this database migration problem (that may not be a problem) in the upcoming weeks.

**Comment by tibonihoo** [comment]
Thanks again for your contribution and I'm i for a double dose of excuses, first for the shameful time it took me to get back to this matter, and also because there was indeed no need to migrate, which I could have known if I had read django's doc (Model field reference) correctly:

> Note that this is different than null. null is purely database-related, whereas blank is validation-related.

**Pull request merged**
